Initial codes
CodeSignal/input-validation pull request #1
Opened 2021-06-02 08:14 UTC by lemur99

2021-06-03 05:28 UTC, Albinutte requested changes
Very cool! I left a few comments, mostly around how the imports will work.

Could you write down in a few words how you expect this module to be used both from the content and from the main repo, and what the module is expected to export? I'm also curious if these changes should block `validator` files from being imported into the main app just yet, because their contents will have to be updated, won't they?

2021-06-03 05:28 UTC, Albinutte commented on README.md
> +### matriixChecks.js
```suggestion
### matrixChecks.js
```

2021-06-03 05:28 UTC, Albinutte commented on README.md
> +### __stringChecks.js__
```suggestion
### stringChecks.js
```

2021-06-03 05:28 UTC, Albinutte commented on index.js
> +};
I'm afraid that in its current form this logic will not work. 

In the content repo, the files are squashed together [in here](https://github.com/CodeSignal/content/blob/6b18900c244c51df1f11e3ec21e12798b3bd56da/_validator/checktaskformat.ts#L872), which basically squashes all files in a single file, and then appends validator file to it. This way, all functions end up in a single file, so both `validator.js` and single "assert" functions have access to one another.

In the current format, there's no way for, say, methods from `graphChecks` to have access to methods like `assert`, or `assertAllInRange`, because it does not import either of them.

If this is meant to be a standalone package that does not require `fs.readFile` magic to work (and also support writing tests for it), the files must be linked correctly, with every file `require`ing their imports explicitly. 

It might also make sense to avoid dumping all helpers into a single `module.export` with spreading, but use named exports:
```js
module.exports  = { arrayChecks, booleanFunctions, ... }
```
, to make sure there are no collisions.

2021-06-03 05:28 UTC, Albinutte commented on package.json
> +}
Please add more fields to `package.json`, at least `license`. You can check out [redux-rags](https://github.com/CodeSignal/redux-rags/blob/master) for example `package.json`, and a `LICENSE` file dumped in there.

2021-06-03 05:28 UTC, Albinutte commented on src/arrayChecks.js
> +      assertInRange(a, b, arr, name);
`assertInRange`, `assertInRangeL`, `assertInRangeR` and `assert` will not work in this file, because they're not imported.

2021-06-03 05:28 UTC, Albinutte commented on src/checkAll.js
> +          assert(func(arr[i][j][k]), message.replace('_element', `${arrName}[${i}][${j}][${k}]`));
`assert` must be imported to work correctly

2021-06-03 05:28 UTC, Albinutte commented on src/graphChecks.js
> +    });
Shouldn't there be a `return` statement here?

2021-06-03 05:28 UTC, Albinutte commented on src/graphChecks.js
> +    });
Shouldn't there be a `return` statement here?

2021-06-03 05:28 UTC, Albinutte commented on src/graphChecks.js
> +      assert(!givenGraph[i][i], `${name} should have no loops`);
`assert`s will not work in this file without import

2021-06-03 05:28 UTC, Albinutte commented on src/matrixChecks.js
> +        assert(
`assert`s will not work in this file without import

2021-06-03 05:28 UTC, Albinutte commented on src/numberChecks.js
> +    assert(number % i !== 0, `${name} should be prime`);
`assert` needs to be imported in this file

2021-06-03 05:28 UTC, Albinutte commented on src/stringChecks.js
> +  assert(
`assert` must be imported here as well

2021-06-03 07:12 UTC, lemur99 commented on src/graphChecks.js
> +    });
We have not used this functions yet. So you are right there is a bug :)

2021-06-03 07:43 UTC, lemur99 commented on index.js
> +};
> It might also make sense to avoid dumping all helpers into a single `module.export` with spreading, but use named exports:
> 
> ```js
> module.exports  = { arrayChecks, booleanFunctions, ... }
> ```

In this way it will be so uncomfortable to create `validate.js`, Since we should write something like that:
```js
const assertFiles = require('@codesignal/input-validation');

assertFiles.arrayChecks.assertAllInRange(1, 3, arr, 'arr');
```

2021-06-03 07:49 UTC, lemur99 commented on index.js
> +};
> In the current format, there's no way for, say, methods from `graphChecks` to have access to methods like `assert`, or `assertAllInRange`, because it does not import either of them.

Why we need to have an access? :)

We have concatenated all the functions in one code for not importing functions in other files. In this way I imported it. For example in `arrayChecks`:

```js
const assert = require('assert');
const assertInRange = require('./numberChecks').assertInRange;
const assertInRangeL = require('./numberChecks').assertInRangeL;
const assertInRangeR = require('./numberChecks').assertInRangeR;
```
Or you want to say that in this way it doesn't work?

2021-06-04 05:43 UTC, Albinutte commented on index.js
> +};
> In this way it will be so uncomfortable to create validate.js, Since we should write something like that:

You will also be able to do this though:
```js
const { arrayChecks } = require('@codesignal/input-validation')`.
```
Not a big deal either way `¯\_(ツ)_/¯`.

> Why we need to have an access? :)

It looks like you've addressed my other comments, so I guess I don't need to answer this question 😄

2021-06-04 05:56 UTC, Albinutte approved these changes
Nice! It would be great to add other helpful tools (ESLint, prettier, tests, types), but we can do it later 👍

2021-06-04 05:56 UTC, Albinutte commented on src/arrayChecks.js
> +const assertInRangeR = require('./numberChecks').assertInRangeR;
There's a shorthand for that:
```suggestion
const { assertInRange, assertInRangeL, assertInRangeL } = require('./numberChecks');
```

2021-06-04 05:56 UTC, Albinutte commented on src/arrayChecks.js
> +  assert
There's a lonely `assert` in here, not sure what it's for 😅

2021-06-04 05:56 UTC, Albinutte commented on src/graphChecks.js
> +function assertConnected(givenGraph, name = 'the graph', representation = 'adjacency-list') {
Doesn't look like `representation` is used here

2021-06-04 07:05 UTC, merged